# Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

 # Reading Data and label

In [2]:
data=pd.read_csv('C:/Users/acer/Downloads/data1.csv',header=None)

In [3]:
label=pd.read_csv('C:/Users/acer/Downloads/label1.csv',header=None)

# Converting into arrays 

In [4]:
npData=np.asarray(data)
#print(npData)
print(npData.ndim)
print(npData.size)
print(npData.shape)

2
400000
(20000, 20)


In [5]:
npLabel=np.asarray(label)
#print(npLabel)
print(npLabel.ndim)
print(npLabel.size)
print(npLabel.shape)

2
20000
(20000, 1)


# Converting labels into OneHotDash form

In [6]:
n_values=np.max((npLabel))+1
print(n_values)
oneHotDash=np.eye(n_values)[npLabel]
oneHotDash=np.reshape(oneHotDash,(20000,5))
print(oneHotDash)

5
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 ..., 
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


# Splitting data into Training, Validation and Testing data

In [7]:
trainData,testDashData=train_test_split(npData,train_size=0.8,test_size=0.2,shuffle=False)
trainLabel,testLabelDash=train_test_split(oneHotDash,train_size=0.8,test_size=0.2,shuffle=False)

In [8]:
validData,testData=train_test_split(testDashData,train_size=0.5,test_size=0.5,shuffle=False)
validLabel,testDash=train_test_split(testLabelDash,train_size=0.5,test_size=0.5,shuffle=False)

In [9]:
print(trainData.shape)
print(validData.shape)
print(testData.shape)
print(validLabel.shape)

(16000, 20)
(2000, 20)
(2000, 20)
(2000, 5)


# Architecture of neurone layer
### neurons in Input layer=20
### neurone in output layer=5

In [10]:
h=input()#number of neurons in the hidden layer
h=int(h)

20


# Initializing weights and baises

In [11]:
std1=(1/np.sqrt(20))#standard deviation of initialiing first weights
std2=(1/np.sqrt(h))#standard deviation of initialiing second weights
w1=np.random.normal(0,std1,(20,h))#gaussian random assignment of weight
w2=np.random.normal(0,std2,(h,5))#gaussian random assignment of weights 
#print("std1\n",std1,"std2\n",std2)
#print("w1\n",w1)
#print("w2\n",w2)
print(w1.shape)
print(w2.shape)



(20, 20)
(20, 5)


In [12]:
b1=np.zeros(h)
b2=np.zeros(5)
print(b1)
print(b2)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]
[ 0.  0.  0.  0.  0.]


# Activation Functions

In [13]:
def actFunc(haha,choose):
    if choose==1:
        return(1/(1+np.exp(-haha)))
    elif choose==2:
        return np.max(0,haha)
    elif choose==3:
        return (np.tanh(haha))
    elif choose==4:
        temp=np.exp(haha)
        return temp/np.sum(temp,axis=1,keepdims=True)


# Forward Pass

In [14]:
def forwardFunc(Data):
    a0=Data
    z1=np.dot(a0,w1)+b1
    a1=actFunc(z1,3)
    z2=np.dot(a1,w2)+b2
    a2=actFunc(z2,4)
    return a0,z1,a1,z2,a2

# Artificial Neural network

In [15]:
epochs=int(input())
batch=int(input())
alpha=0.001

20
1600


## Cost function

In [16]:
def costFunc(y,t):
    return -(t*(np.log(y))+(1-t)*np.log(1-y))

## Accuracy function

In [17]:
def accuracyFunc(output,labelData,dataSize):
    maxInRow=np.argmax(output, axis=1)
    maxInLabels=np.argmax(labelData, axis=1)
    ones=np.equal(maxInRow,maxInLabels)
    count=np.sum(ones)
    return (count/dataSize)*100

# Backward pass

In [23]:
for j in range(epochs):
    for i in range(100):
        a0,z1,a1,z2,a2=forwardFunc(trainData[i*batch:(i+1)*batch,:])
        y=a2
        labelBatch=trainLabel[i*batch:(i+1)*batch,:]
        #BackwardPass
        del2=y-labelBatch
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb1=np.sum(del1,axis=0)
        dcdb2=np.sum(del2,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b2=b2-alpha*dcdb2
        b1=b1-alpha*dcdb1
    #Cost after one epoch
    a0,z1,a1,z2,a2=forwardFunc(trainData)
    ytrue=a2
    cost=np.sum(costFunc(ytrue,trainLabel))/16000
    print ("cost = ",end="")
    print (cost)
    accuracy = accuracyFunc(ytrue,trainLabel,16000.0)
    print ("training accuracy = ", end="")
    print (accuracy)
    ##validation
va0,vz1,va1,vz2,va2=forwardFunc(validData)
vOutput=va2
accuracy = accuracyFunc(vOutput,validLabel,2000.0)
print ("validation accuracy ")
print (accuracy)
        

cost = 0.461550384334
training accuracy = 91.50625
cost = 0.46119513699
training accuracy = 91.48125
cost = 0.460841156753
training accuracy = 91.4625
cost = 0.460488253914
training accuracy = 91.475
cost = 0.46013630597
training accuracy = 91.50625
cost = 0.459785258122
training accuracy = 91.51875
cost = 0.459435122321
training accuracy = 91.5125
cost = 0.459085974555
training accuracy = 91.50625
cost = 0.458737950184
training accuracy = 91.51875
cost = 0.45839123729
training accuracy = 91.53125
cost = 0.458046068203
training accuracy = 91.54375
cost = 0.457702709528
training accuracy = 91.55
cost = 0.457361451157
training accuracy = 91.58125
cost = 0.457022594832
training accuracy = 91.5875
cost = 0.456686442875
training accuracy = 91.58125
cost = 0.456353287671
training accuracy = 91.58125
cost = 0.456023402434
training accuracy = 91.5875
cost = 0.455697033671
training accuracy = 91.60625
cost = 0.455374395605
training accuracy = 91.60625
cost = 0.455055666673
training accuracy = 9